// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'core/config/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: EnvConfig.requiredString('FIREBASE_WEB_API_KEY'),
    appId: EnvConfig.requiredString('FIREBASE_WEB_APP_ID'),
    messagingSenderId: EnvConfig.requiredString(
      'FIREBASE_WEB_MESSAGING_SENDER_ID',
    ),
    projectId: EnvConfig.requiredString('FIREBASE_WEB_PROJECT_ID'),
    authDomain: EnvConfig.requiredString('FIREBASE_WEB_AUTH_DOMAIN'),
    storageBucket: EnvConfig.requiredString('FIREBASE_WEB_STORAGE_BUCKET'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: EnvConfig.requiredString('FIREBASE_ANDROID_API_KEY'),
    appId: EnvConfig.requiredString('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: EnvConfig.requiredString(
      'FIREBASE_ANDROID_MESSAGING_SENDER_ID',
    ),
    projectId: EnvConfig.requiredString('FIREBASE_ANDROID_PROJECT_ID'),
    storageBucket: EnvConfig.requiredString('FIREBASE_ANDROID_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: EnvConfig.requiredString('FIREBASE_IOS_API_KEY'),
    appId: EnvConfig.requiredString('FIREBASE_IOS_APP_ID'),
    messagingSenderId: EnvConfig.requiredString(
      'FIREBASE_IOS_MESSAGING_SENDER_ID',
    ),
    projectId: EnvConfig.requiredString('FIREBASE_IOS_PROJECT_ID'),
    storageBucket: EnvConfig.requiredString('FIREBASE_IOS_STORAGE_BUCKET'),
    iosBundleId: EnvConfig.requiredString('FIREBASE_IOS_BUNDLE_ID'),
  );
}
